/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "LED_Control.h"
#include "Button_Control.h"
#include "Button_Interrupt.h"
#include "Timer.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

/* Interrupt Service Routine */
// Interrupt ID : 0x0E, Target CPU : CPU0, Trigger Event : T12 PM
__interrupt(SRPN_TIMER0) __vector_table(0)
void CCU60_T12_ISR(void){

    P10_OUT.U ^= ( 0x1 << LED_D13_OUT_BIT_LSB_IDX ); // toggle LED1

    static unsigned int mode = 0;

    switch(mode) {
        case 0:
            P10_OUT.U |=  ( 0x1 << RGB_D11_OUT_BIT_LSB_IDX ); // set Red LED
            P10_OUT.U &= ~( 0x1 << RGB_D10_OUT_BIT_LSB_IDX ); // clear Green LED
            P02_OUT.U &= ~( 0x1 << RGB_D09_OUT_BIT_LSB_IDX ); // clear Blue LED
            break;
        case 1:
            P10_OUT.U &= ~( 0x1 << RGB_D11_OUT_BIT_LSB_IDX ); // clear Red LEDs
            P10_OUT.U |=  ( 0x1 << RGB_D10_OUT_BIT_LSB_IDX ); // set Green LED
            P02_OUT.U &= ~( 0x1 << RGB_D09_OUT_BIT_LSB_IDX ); // clear Blue LED
            break;
        case 2:
            P10_OUT.U &= ~( 0x1 << RGB_D11_OUT_BIT_LSB_IDX ); // clear Red LED
            P10_OUT.U &= ~( 0x1 << RGB_D10_OUT_BIT_LSB_IDX ); // clear Green LED
            P02_OUT.U |=  ( 0x1 << RGB_D09_OUT_BIT_LSB_IDX ); // set Blue LED
            break;
    }

    if(mode < 2)
        mode++;
    else
        mode = 0;
}

// Interrupt ID : 0x10, Target CPU : CPU0, Trigger Event : Falling-edge
__interrupt(SRPN_BUTTON1) __vector_table(0)
void ERU2_ISR(void) {
    CCU60_IEN.U ^= ( 0x1 << IEN_ENT12PM_BIT_LSB_IDX );  // toggle enable T12 Period-Match Interrupt

    P10_OUT.U &= ~( 0x1 << LED_D13_OUT_BIT_LSB_IDX );   // clear LED1
    P10_OUT.U &= ~( 0x1 << LED_D12_OUT_BIT_LSB_IDX );   // clear LED2
}

// Interrupt ID : 0x0F, Target CPU : CPU0, Trigger Event : Rising/Falling-edge
__interrupt(SRPN_BUTTON2) __vector_table(0)
void ERU0_ISR(void) {

    /* Toggle Period Match between 2 state */
    if((P02_IN.U & BUTTON_D3_IN_MASK) != BUTTON_D3_IN_MASK) { // Check button is pressed(pull-up switch)
        CCU60_T12PR.U = (unsigned short)( ( ( CLOCK_CYCLE_SHIFT_SIGN )
                    ? ( CCU60_MODIFIED_FREQ >> CLOCK_CYCLE_SHIFT_VAL )
                    : ( CCU60_MODIFIED_FREQ << CLOCK_CYCLE_SHIFT_VAL )
                      ) >> 2 ) - 1;

        P10_OUT.U |= ( 0x1 << LED_D12_OUT_BIT_LSB_IDX );    // set LED2
    }
    else {
        CCU60_T12PR.U = (unsigned short)( ( CLOCK_CYCLE_SHIFT_SIGN )
                    ? ( CCU60_MODIFIED_FREQ >> CLOCK_CYCLE_SHIFT_VAL )
                    : ( CCU60_MODIFIED_FREQ << CLOCK_CYCLE_SHIFT_VAL )
                      ) - 1;

        P10_OUT.U &= ~( 0x1 << LED_D12_OUT_BIT_LSB_IDX );   // clear LED2
    }

    /* Load T12PR from shadow Register */
    CCU60_TCTR4.U |= ( 0x1 << TCTR4_T12STR_BIT_LSB_IDX );   // transfer shadow reg. from STE12 to T12

}


int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    /* Initialization */
    initLED();
    initRGBLED();

    initButton();
    initInterrupt_Button1();
    initInterrupt_Button2();

    initTimer();

    while(1);

    return (1);
}
