/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "LED_Control.h"
#include "Button_Control.h"
#include "Button_Interrupt.h"
#include "Timer.h"
#include "VADC.h"
#include "PWM.h"
#include "Ultrasonic.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

/* External Global Variable */
unsigned int range;
unsigned char range_valid_flag;

/* Interrupt Service Routine */
__interrupt(SRPN_CCU60) __vector_table(0)
void CCU60_T12_ISR(void) {
    // set TRIG pin(P02.6) as Low
    P02_OUT.B.P6 &= 0x0;
}

__interrupt(SRPN_CCU61) __vector_table(0)
void ERU0_ISR(void) {
    if( P00_IN.B.P4 != 0 ){
        CCU61_TCTR4.B.T12RS = 0x1; // set Request CCU61 T12 Counter
    }
    else {
        CCU61_TCTR4.B.T12RR = 0x1;  // reset Request CCU61 T12 Counter

        range = ( ( CCU61_T12.B.T12CV * 1000000 ) / 48828 ) / 58;
        range_valid_flag = 1;

        CCU61_TCTR4.B.T12RES = 0x1; // reset CCU61 T12 Counter
    }
}

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    /* Initialization */
    // LED1, 2 : P10.1, P10.2 (P10_IOCR0)
//    initLED();

    // RGB LED : P2.7, P10.5, P10.3 (P2_IOCR4, P10_IOCR0)
    initRGBLED();

    // Button : P2.0, P2.1 (P2_IOCR0)
//    initButton();

    // Button edge-triggered interrupt : P2.0, 1 (ERS0, 2 ; EICR1)
//    initInterrupt_Button1();
//    initInterrupt_Button2();

    // VADC : SAR 4.7 (Group 4 Channel 7, AN39)
//    initVADC_SAR4_7();

    // Timer triggered interrupt : CCU60, CCU61
    initTimer_CCU60();
    initTimer_CCU61();

    // GTM(for LED 1,2 PWM) : P10.1(TOUT103 ; LED2), P10.2(TOUT104 ; LED1)
//    initLED1_PWM();
//    initGTM();
//    initGTM(PORT_10_1);
//    initGTM(PORT_10_2);

    // GTM(for RGB LED PWM) : P2.7(TOUT7 ; Blue), P10.5(TOUT107 ; Green), P10.3(TOUT105 ; Red)
//    initRGBLED_PWM();
//    initGTM(PORT_2_7);
//    initGTM(PORT_10_5);
//    initGTM(PORT_10_3);

    // GTM for Buzzer : P2.3(TOUT3)
//    initBuzzer_PWM();
//    initGTM(PORT_2_3);

    // ERU for Ultra-Sonic
    initInterrupt_CCU61();
    initUltrasonic();

    /* Start generating PWM signal for each GPIO port */
//    startPWM(PORT_10_1);
//    startPWM(PORT_10_2);
//    startPWM(PORT_2_3);


    while(1) {
        for(unsigned int i = 0; i < 10000000 ; i++);

        trigUltrasonic();

        while( range_valid_flag == 0 );

        if(range >= 60) {
            P10_OUT.U |=  ( 0x1 << RGB_D11_OUT_BIT_LSB_IDX ); // set Red LED
            P10_OUT.U &= ~( 0x1 << RGB_D10_OUT_BIT_LSB_IDX ); // clear Green LED
            P02_OUT.U &= ~( 0x1 << RGB_D09_OUT_BIT_LSB_IDX ); // clear Blue LED
        }
        else if(range >= 40) {
            P10_OUT.U &= ~( 0x1 << RGB_D11_OUT_BIT_LSB_IDX ); // clear Red LED
            P10_OUT.U |=  ( 0x1 << RGB_D10_OUT_BIT_LSB_IDX ); // set Green LED
            P02_OUT.U &= ~( 0x1 << RGB_D09_OUT_BIT_LSB_IDX ); // clear Blue LED
        }
        else if(range >= 20) {
            P10_OUT.U &= ~( 0x1 << RGB_D11_OUT_BIT_LSB_IDX ); // clear Red LED
            P10_OUT.U &= ~( 0x1 << RGB_D10_OUT_BIT_LSB_IDX ); // clear Green LED
            P02_OUT.U |=  ( 0x1 << RGB_D09_OUT_BIT_LSB_IDX ); // set Blue LED
        }
        else {
            P10_OUT.U &= ~( 0x1 << RGB_D11_OUT_BIT_LSB_IDX ); // clear Red LED
            P10_OUT.U &= ~( 0x1 << RGB_D10_OUT_BIT_LSB_IDX ); // clear Green LED
            P02_OUT.U &= ~( 0x1 << RGB_D09_OUT_BIT_LSB_IDX ); // clear Blue LED
        }
    }

    return (1);
}
